### ISSUE TITLE
reactjs font awesome 5 doesn't work

### ISSUE THREAD

**Issue by designxtek** [androberts/mushroom-decision-trees#1]
Does not update on the DOM when isToggleOn changes
```
render() {
        const isToggleOn = this.state.isToggleOn;
        let radioIcon = null;

        if (isToggleOn) {
            radioIcon = <i className="fas fa-dot-circle product-package-item-radio--selected"></i>;
        } else {
            radioIcon = <i className="far fa-circle product-package-item-radio"></i>;
        }
...
```

Updates if the element is wrapped in div/span. Seems like if it detects a new wrapped element then it will render.
```
render() {
        const isToggleOn = this.state.isToggleOn;
        let radioIcon = null;

        if (isToggleOn) {
            radioIcon = <i className="fas fa-dot-circle product-package-item-radio--selected"></i>;
        } else {
            radioIcon = <span><i className="far fa-circle product-package-item-radio"></i></span>;
        }
...
```

**Comment by androberts** [comment]
You must perform all state changes through `this.setState`. How are you changing `isToggleOn`?

**Comment by designxtek** [comment]
Using this.setState. I think Font Awesome 5 uses JS to manipulate the dom and it conflicts w/ ReactJS

**Comment by androberts** [comment]
Also, no need for two different elements, just do `<i className={"fas fa-dot-circle" + isToggleOn ? " product-package-item-radio--selected" : "" }>`

**Comment by designxtek** [comment]
I'll try that. Seems like a font awesome js + reactjs bug. It loads the first time but the className won't change. I forced a change by adding a <span> wrapper but that just breaks the DOM

**Comment by designxtek** [comment]
oh weird it works in my jsfiddle:

https://jsfiddle.net/d3jy3ngv/5/
